name: Deploy Flask App to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.LIGHTSAIL_SSH_KEY }}

      - name: Deploy Flask App
        run: |
          ssh -o StrictHostKeyChecking=no bitnami@63.178.152.99 << 'EOF'
          cd ~
          if [ ! -d "misafirinvarFrontendWeb" ]; then
            git clone https://github.com/mertmetin1/misafirinvarFrontendWeb.git
          fi
          cd misafirinvarFrontendWeb
          git pull origin main
          nohup python3 app.py > log.out 2>&1 &
          EOF
