name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.LIGHTSAIL_SSH_KEY }}

      - name: Deploy to Lightsail via SSH
        run: |
          ssh -o StrictHostKeyChecking=no bitnami@63.178.152.99 << 'EOF'
          cd /home/bitnami/misafirinvar-frontend
          git pull origin main
          sudo systemctl restart nginx
          EOF
